service:
  name: adotebot

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless
  environment:
    DYNAMODB_TABLE: ${file(./env.yml):DYNAMODB_TABLE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  collectTweets:
    handler: src/collectTweets.handler
    description: Collect Tweets about pets up for adoption and save them to DynamoDB
    events:
      - schedule: rate(1 hour)
    environment:
      TWITTER_CONSUMER_KEY: ${file(./env.yml):TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${file(./env.yml):TWITTER_CONSUMER_SECRET}
      TWITTER_ACCESS_TOKEN: ${file(./env.yml):TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_TOKEN_SECRET: ${file(./env.yml):TWITTER_ACCESS_TOKEN_SECRET}

resources:
  Resources:
    CollectedTweetsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(./env.yml):DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
          - AttributeName: review_status
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ReviewStatusIndex
            KeySchema:
              - AttributeName: review_status
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY
            ProvisionedThroughput:
              ReadCapacityUnits: 2
              WriteCapacityUnits: 2
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
